# Generated by Django 2.2.4 on 2020-03-17 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200316_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default=None, max_length=255)),
                ('merchant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Merchant')),
            ],
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
