# Generated by Django 2.2.4 on 2020-03-19 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200317_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('order_subtotal', models.FloatField()),
                ('taxes', models.FloatField()),
                ('order_total', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_time', models.DateTimeField(default=datetime.datetime(2020, 3, 19, 19, 38, 58, 827111))),
                ('items', models.ManyToManyField(to='core.Item')),
                ('merchant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Merchant')),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Store')),
            ],
        ),
    ]
