# Generated by Django 2.2.10 on 2020-04-01 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200320_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 12, 42, 40, 542259)),
        ),
    ]
