# Generated by Django 2.2.13 on 2021-02-20 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200401_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 20, 54, 48, 566873)),
        ),
    ]
